### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by Piyush7890** [Adonai/jaudiotagger#2]
java.lang.NoClassDefFoundError: org.jcodec.containers.mp4.boxes.-$$Lambda$MetaBox$_x1Oj-KqH3YEGolNwgoJCD8aMYM
        at org.jcodec.containers.mp4.boxes.MetaBox.getItunesMeta(MetaBox.java:77)
        at org.jaudiotagger.audio.mp4.Mp4TagReader.createMp4Field(Mp4TagReader.java:153)
        at org.jaudiotagger.audio.mp4.Mp4TagReader.read(Mp4TagReader.java:132)
        at org.jaudiotagger.audio.mp4.Mp4FileReader.getTag(Mp4FileReader.java:43)
        at org.jaudiotagger.audio.generic.AudioFileReader.read(AudioFileReader.java:103)
        at org.jaudiotagger.audio.AudioFileIO.readFile(AudioFileIO.java:322)
        at org.jaudiotagger.audio.AudioFileIO.read(AudioFileIO.java:177)

computeIfAbsent() method was added in api 24, so it wont work below api 24
Same goes with the stream() and filter() methods

**Comment by Piyush7890** [comment]
Thankyou for fixing it quick!! really appreciate the work you have done here
